=== s-scotto/Codifica-di-Testi/esempio_dtd.dtd
<!--Simona Scotto di Perrotolo 501018-->

<!--Denire i seguenti elementi:
elemento root: TEI
elementi gli:
header (obbligatorio una occorrenza)
facsimile (opzionale una occorrenza)
text (obbligatorio almeno una occorrenza)
Gli elementi header, facsimile e text hanno tutti un content
model testuale-->

<!ELEMENT root (TEI)>
<!ELEMENT TEI (header, facsimile?, text+)>
<!ELEMENT header (#PCDATA)>
<!ELEMENT facsimile (#PCDATA)>
<!ELEMENT text (#PCDATA)>

=== s-scotto/Codifica-di-Testi/xml_per_dtd.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- Simona Scotto di Perrotolo 504018-->
<!-- file xml di prova per esercizio di validazione dtd del file esempio_dtd.dtd -->
<!DOCTYPE root SYSTEM "esempio_dtd.dtd">
<root>
    <TEI>
        <header type="intestazione" lang="en">
            ...     
        </header>
        <facsimile source="https://www.w3c.it/" ref="testo2 testo3"> 
            ...
        </facsimile>
        <text id="testo1"> 
            ... 
        </text>
        <text id="testo2" type="poetry">
            ...
        </text>
        <text id="testo3" type="description">
            <seg> ... </seg>
        </text>
    </TEI>
</root>
